ALTER TABLE rechnung ADD COLUMN mwst DECIMAL(4,2) NULL;
UPDATE rechnung SET mwst = 19.0 WHERE mwst IS NULL;
ALTER TABLE "PUBLIC"."RECHNUNG" ALTER COLUMN mwst SET NOT NULL;

ALTER TABLE angebot ADD COLUMN mwst DECIMAL(4,2) NULL;
UPDATE angebot SET mwst = 19.0 WHERE mwst IS NULL;
ALTER TABLE "PUBLIC"."ANGEBOT" ALTER COLUMN mwst SET NOT NULL;